config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :patients
  resources :appointments


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  validates_presence_of :time, :patient
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments
  validates_presence_of :first_name, :last_name
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:

  has_many :patients
  has_many :appointments, through: :patients
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || appointments_path
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = current_user.appointments
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.user = current_user

  end

  def edit
  end

  def update
  end

  def delete
  end

  private

  def appointment_params
    params.require(:appointment).permit(:time, :patient)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = current_user.patients
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
    @user = current_user
  end

  def create
    @patient = Patient.new(patient_params)
    @user = current_user
    @patient.user = @user
    if @patient.save
      redirect_to patients_path
    else
      render :new
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:name, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for @appointment, method: :post, remote: true do |f| %>

  <%= f.input :time, label: "date and time", label_html: { class: 'my_class' } %>
  <%= f.input :patient, label: "patient name", collection: current_user.patients.name %>
  <%= f.button :submit %>
<% end %>

app/views/appointments/_table.html.erb
<tr class="pretty-row">
  <td class="row-left-element">
    <%= appointment.id %>
  </td>

  <td class="row-middle-element">
    <%= appointment.time %>
    <!-- <input class="check-box" type="checkbox" checked=""> -->
  </td>

  <td class="row-right-element">
    <%= appointment.patient.first_name %> <%= appointment.patient.last_name %>
  </td>

</tr>

app/views/appointments/edit.html.erb
<h1>Appointments#edit</h1>
<p>Find me in app/views/appointments/edit.html.erb</p>

app/views/appointments/index.html.erb
<div class="button-box">
  <button class="trigger">
    <div class="text-button-trigger">
      add a new appointment <i class="fas fa-plus-circle"></i>
    </div>

  </button>
</div>

<div class="requests-body">
    <!-- HEADERS -->
    <table class="pretty-table">
      <thead>
        <tr>
          <td><h1>ID</h1></td>
          <td><h1>DATE & TIME</h1></td>
          <td><h1>PATIENT</h1></td>
        </tr>
      </thead>
      <tbody>
        <% @appointments.each do |appointment| %>
          <%= render 'appointments/table', appointment: appointment %>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Docmate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients#index</h1>
<p>Find me in app/views/patients/index.html.erb</p>

<%= link_to new_patient_path do %>
  <p>new patient</p>
<% end %>

<% @patients.each do |patient| %>
  <li><%= patient.name %></li>
<% end %>

app/views/patients/new.html.erb
<%= simple_form_for @patient, method: :post do |f| %>
  <%= f.input :name, label: "patient name" %>
  <%= f.input :notes, label: "notes" %>
  <%= f.button :submit %>
<% end %>

app/views/patients/show.html.erb
<h1>Patients#show</h1>
<p>Find me in app/views/patients/show.html.erb</p>